name: slcl1butils-tests
channels:
  - conda-forge
dependencies:
  - python
  # development
  - ipython
  - pre-commit
  - jupyterlab
  - jupyterlab_code_formatter
  - isort
  - black
  - dask-labextension
  # testing
  - pytest
  - pytest-reportlog
  - pytest-cov
  - hypothesis
  - coverage
  # I/O
  - h5netcdf
  - zarr
  - scipy
  - fsspec
  # data
  - xarray
  - dask
  - numpy
  - pandas
  - shapely
  # processing
  - more-itertools
  - tqdm
  - importlib_resources
  # plotting
  - holoviews
  - geoviews
