name: slcl1butils-tests
channels:
  - conda-forge
dependencies:
  - python=3.10
  # development
  - ipython
  - pre-commit
  - jupyterlab
  - jupyterlab_code_formatter
  - isort
  - black
  - dask-labextension
  # testing
  - pytest
  - pytest-reportlog
  - hypothesis
  - coverage
  # I/O
  - h5netcdf
  - zarr
  - scipy
  # data
  - xarray
  - xarray-datatree
  - dask
  - numpy
  - pandas
  - shapely
  # processing
  - more-itertools
  - tqdm
  - importlib_resources